# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: gh-page deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Set Actions Allow Unsecure Commands
      # run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Installing Yarn
        run: npm i -g yarn

      - name: Installing my packages
        run: yarn

      - name: Build my App
        run: yarn build
      # - run: touch ./out/.nojekyll

      - name: Deploy 🚀
        # uses: peaceiris/actions-gh-pages@v3
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          folder: build # The folder the action should deploy.